#Properties  
# Http Client Configutation
tomcat:
  ajp:
    protocol: "AJP/1.3"
    port: 13001
    enabled: true

access:
  denied:
    url: "/login"

login:
  success:
    url: "/home"
  default:
    url: "/login"

http:
  client:
    max:
      total-connection: 20
      per-route: 5

namu:
  media:
    tiles: /WEB-INF/tiles/tiles.xml 
    upload-path: /nasa12345/files/
  verifyEmail : http://media.net/verifyEmail
  
resources:
  location:
    video : D:/RPA/
#    video : /usr/local/barun-webserver/academy/resource/video/
  uri:
    video : /user/lecture/resource/video/

scheduler:
  is:
    running: false

#Spring Default Configuration
spring:
  application:
    name: com.anchordata.webframework
      
  messages:
    cache-duration: -1 
    basename: classpath:/config/message.properties
    encoding: UTF-8
   
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
      
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp 

  main:
    datasource:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:mysql://103.55.191.104:3306/barun_academy?serverTimezone=UTC&characterEncoding=UTF-8&allowMultiQueries=true
#      jdbc-url: jdbc:log4jdbc:mysql://localhost:3306/barun?serverTimezone=UTC&characterEncoding=UTF-8&allowMultiQueries=true
      username: anchor
      password: Anchoruser0914@
      hikari:
        max-lifetime: 1200000
        maximum-pool-size: 12
        minimum-idle: 5 
        idle-timeout: 30000  
        connection-test-query: SELECT 1    
              
  cache:
    ehcache:
      config: classpath:/config.ehcache.xml
    
  devtools:
    livereload:
      enabled: true
  
  google:
    client:
      clientId: 744744614208-obapm74n0kn9ug54len0a838am3ct75l.apps.googleusercontent.com
      clientSecret: KYaQUpkFq_u-jNNBZ1Ju_1KE
      accessTokenUri: https://www.googleapis.com/oauth2/v4/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
      clientAuthenticationScheme: form
      scope: email, profile
    resource:
      userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
    recaptcha:
      siteKey: 6LdGVgEVAAAAAJz8oWKmIs5kHyp5qwCRQo5-XYEA
      secretKey: 6LdGVgEVAAAAAKgzxwUdumjFDsvk2jASX1ieBp3X
